version: 0.0
os: linux
files:
  - source: /
    destination: /srv/blockv.io
hooks:
  ApplicationStart:
    - location: service nginx start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: service nginx stop
      timeout: 300
      runas: root
