version: 0.0
os: linux
files:
  - source: /www
    destination: /srv/blockv.io
  - source: /nginx
    destination: /etc/nginx
  - source: /scripts
    destination: /srv/blockv.io/scripts
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/clear_cache.sh
      timeout: 380
