version: 0.0
os: linux
files:
  - source:
    destination: /srv/blockv.io
hooks:
  ApplicationStart:
    - location: /etc/init.d/nginx start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /etc/init.d/nginx stop
      timeout: 300
      runas: root
